package com.avalonnarrator.domain.model

enum class SetupIssueCode {
    PERCIVAL_WITHOUT_MERLIN,
    MORGANA_WITHOUT_PERCIVAL,
    MERLIN_WITHOUT_ASSASSIN,
    LANCELOT_PAIR_REQUIRED,
    MESSENGER_TRIO_REQUIRED,
    ROGUE_PAIR_REQUIRED,
    SORCERER_PAIR_REQUIRED,
    TEAM_RATIO_INVALID,
    MIN_PLAYERS_NOT_MET,
    MAX_PLAYERS_EXCEEDED,
}
