package com.avalonnarrator.domain.roles

import com.avalonnarrator.domain.setup.GameModule

object RoleCatalog {
    private val roles: Map<RoleId, RoleDefinition> = listOf(
        RoleDefinition(
            id = RoleId.MERLIN,
            name = "Merlin",
            alignment = Alignment.GOOD,
            imageKey = "merlin",
            mechanicSummary = "Reveal: Sees Evil players except Mordred (and any module-hidden Evil roles). Endgame: If Assassin correctly names Merlin after 3 successful quests, Evil wins.",
            tags = setOf("information", "core"),
        ),
        RoleDefinition(
            id = RoleId.PERCIVAL,
            name = "Percival",
            alignment = Alignment.GOOD,
            imageKey = "percival",
            mechanicSummary = "Reveal: Sees two Merlin candidates (Merlin and Morgana), but cannot distinguish which one is Merlin.",
            tags = setOf("information", "core"),
        ),
        RoleDefinition(
            id = RoleId.CLERIC,
            name = "Cleric",
            alignment = Alignment.GOOD,
            imageKey = "cleric",
            mechanicSummary = "Reveal: Learns whether the starting Leader is Good or Evil. Loyalty Check: This information can be altered by lying roles such as Trickster/Troublemaker.",
            tags = setOf("information", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.TROUBLEMAKER,
            name = "Troublemaker",
            alignment = Alignment.GOOD,
            imageKey = "troublemaker",
            mechanicSummary = "Loyalty Check: Must give false alignment information whenever their loyalty is checked.",
            tags = setOf("deception", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.SENIOR_MESSENGER,
            name = "Senior Messenger",
            alignment = Alignment.GOOD,
            imageKey = "senior_messenger",
            mechanicSummary = "Reveal (Messengers): Learns Junior Messenger's identity.",
            tags = setOf("messenger", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.JUNIOR_MESSENGER,
            name = "Junior Messenger",
            alignment = Alignment.GOOD,
            imageKey = "junior_messenger",
            mechanicSummary = "Reveal (Messengers): Is seen by Senior Messenger, but does not learn Senior Messenger's identity.",
            tags = setOf("messenger", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.UNTRUSTWORTHY_SERVANT,
            name = "Untrustworthy Servant",
            alignment = Alignment.GOOD,
            imageKey = "untrustworthy_servant",
            mechanicSummary = "Reveal: Knows Assassin. Quest: Cannot play Fail. Recruitment/Endgame: After 3 successful quests, Assassin may recruit them; if the recruitment guess is correct, they become Evil and perform assassination.",
            tags = setOf("deception", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.ROGUE_GOOD,
            name = "Good Rogue",
            alignment = Alignment.GOOD,
            imageKey = "rogue_good",
            mechanicSummary = "Quest (Rogue): May play Rogue Success. Victory Check: Claims immediate individual victory by playing Rogue Success on the 3rd successful quest after at least one earlier successful quest.",
            tags = setOf("rogue", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.SORCERER_GOOD,
            name = "Good Sorcerer",
            alignment = Alignment.GOOD,
            imageKey = "sorcerer_good",
            mechanicSummary = "Quest (Sorcerers): May play Magic to invert quest resolution. Resolution: An odd number of Magic cards flips Success/Fail.",
            tags = setOf("sorcerer", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.LOYAL_SERVANT,
            name = "Loyal Servant",
            alignment = Alignment.GOOD,
            imageKey = "loyal_servant",
            mechanicSummary = "Standard role with no special abilities.",
            tags = setOf("core"),
        ),
        RoleDefinition(
            id = RoleId.ASSASSIN,
            name = "Assassin",
            alignment = Alignment.EVIL,
            imageKey = "assassin",
            mechanicSummary = "Endgame: After 3 successful quests, names one player as Merlin. If correct, Evil wins immediately.",
            tags = setOf("core", "kill"),
        ),
        RoleDefinition(
            id = RoleId.MORGANA,
            name = "Morgana",
            alignment = Alignment.EVIL,
            imageKey = "morgana",
            mechanicSummary = "Reveal: Appears as Merlin to Percival.",
            tags = setOf("deception", "core"),
        ),
        RoleDefinition(
            id = RoleId.MORDRED,
            name = "Mordred",
            alignment = Alignment.EVIL,
            imageKey = "mordred",
            mechanicSummary = "Reveal: Hidden from Merlin.",
            tags = setOf("stealth", "core"),
        ),
        RoleDefinition(
            id = RoleId.OBERON,
            name = "Oberon",
            alignment = Alignment.EVIL,
            imageKey = "oberon",
            mechanicSummary = "Reveal: Unknown to other Evil players and does not learn them.",
            tags = setOf("chaos", "core"),
        ),
        RoleDefinition(
            id = RoleId.LUNATIC,
            name = "Lunatic",
            alignment = Alignment.EVIL,
            imageKey = "lunatic",
            mechanicSummary = "Quest: Must play Fail on every quest they join.",
            tags = setOf("expansion"),
        ),
        RoleDefinition(
            id = RoleId.BRUTE,
            name = "Brute",
            alignment = Alignment.EVIL,
            imageKey = "brute",
            mechanicSummary = "Quest: May play Fail only on Quests 1-3; on Quests 4-5 must play Success.",
            tags = setOf("expansion"),
        ),
        RoleDefinition(
            id = RoleId.TRICKSTER,
            name = "Trickster",
            alignment = Alignment.EVIL,
            imageKey = "trickster",
            mechanicSummary = "Loyalty Check: May lie whenever their alignment is checked.",
            tags = setOf("deception", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.REVEALER,
            name = "Revealer",
            alignment = Alignment.EVIL,
            imageKey = "revealer",
            mechanicSummary = "Quest Trigger: Must publicly reveal identity immediately after the second failed quest.",
            tags = setOf("expansion"),
        ),
        RoleDefinition(
            id = RoleId.EVIL_MESSENGER,
            name = "Evil Messenger",
            alignment = Alignment.EVIL,
            imageKey = "evil_messenger",
            mechanicSummary = "Quest (Messengers): Can submit Success, Fail, or Evil Message according to module rules.",
            tags = setOf("messenger", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.ROGUE_EVIL,
            name = "Evil Rogue",
            alignment = Alignment.EVIL,
            imageKey = "rogue_evil",
            mechanicSummary = "Quest (Rogue): May play Rogue Fail. Victory Check: Claims immediate individual victory by playing Rogue Fail on the 3rd failed quest after at least one earlier failed quest.",
            tags = setOf("rogue", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.SORCERER_EVIL,
            name = "Evil Sorcerer",
            alignment = Alignment.EVIL,
            imageKey = "sorcerer_evil",
            mechanicSummary = "Quest (Sorcerers): May play Success or Magic, but cannot play Fail. Reveal (optional): Can be hidden from Merlin.",
            tags = setOf("sorcerer", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.MINION,
            name = "Minion",
            alignment = Alignment.EVIL,
            imageKey = "minion",
            mechanicSummary = "Standard role with no special abilities.",
            tags = setOf("core"),
        ),
        RoleDefinition(
            id = RoleId.LANCELOT_GOOD,
            name = "Good Lancelot",
            alignment = Alignment.GOOD,
            imageKey = "lancelot_good",
            mechanicSummary = "Reveal (Lancelot): Starts Good. Variant Trigger: May switch allegiance during Lancelot allegiance-change rules.",
            modules = setOf(GameModule.LANCELOT),
            tags = setOf("module", "lancelot"),
        ),
        RoleDefinition(
            id = RoleId.LANCELOT_EVIL,
            name = "Evil Lancelot",
            alignment = Alignment.EVIL,
            imageKey = "lancelot_evil",
            mechanicSummary = "Reveal (Lancelot): Starts Evil. Variant Trigger: May switch allegiance during Lancelot allegiance-change rules.",
            modules = setOf(GameModule.LANCELOT),
            tags = setOf("module", "lancelot"),
        ),
    ).associateBy(RoleDefinition::id)

    fun all(): List<RoleDefinition> = roles.values.sortedBy { it.name }

    fun byId(id: RoleId): RoleDefinition? = roles[id]

    fun byAlignment(alignment: Alignment): List<RoleDefinition> =
        roles.values.filter { it.alignment == alignment }.sortedBy { it.name }
}
