package com.avalonnarrator.domain.roles

import com.avalonnarrator.domain.setup.GameModule

object RoleCatalog {
    private val roles: Map<RoleId, RoleDefinition> = listOf(
        RoleDefinition(
            id = RoleId.MERLIN,
            name = "Merlin",
            alignment = Alignment.GOOD,
            imageKey = "merlin",
            mechanicSummary = "Knows most evil players. Must remain hidden from the Assassin.",
            tags = setOf("information", "core"),
        ),
        RoleDefinition(
            id = RoleId.PERCIVAL,
            name = "Percival",
            alignment = Alignment.GOOD,
            imageKey = "percival",
            mechanicSummary = "Sees Merlin and Morgana but cannot tell which is which.",
            tags = setOf("information", "core"),
        ),
        RoleDefinition(
            id = RoleId.CLERIC,
            name = "Cleric",
            alignment = Alignment.GOOD,
            imageKey = "cleric",
            mechanicSummary = "Secretly checks loyalty information about the first leader.",
            tags = setOf("information", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.TROUBLEMAKER,
            name = "Troublemaker",
            alignment = Alignment.GOOD,
            imageKey = "troublemaker",
            mechanicSummary = "A loyal role with a forced misinformation constraint.",
            tags = setOf("deception", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.SENIOR_MESSENGER,
            name = "Senior Messenger",
            alignment = Alignment.GOOD,
            imageKey = "senior_messenger",
            mechanicSummary = "Sees the Junior Messenger during reveal.",
            tags = setOf("messenger", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.JUNIOR_MESSENGER,
            name = "Junior Messenger",
            alignment = Alignment.GOOD,
            imageKey = "junior_messenger",
            mechanicSummary = "Signals to Senior Messenger during reveal.",
            tags = setOf("messenger", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.UNTRUSTWORTHY_SERVANT,
            name = "Untrustworthy Servant",
            alignment = Alignment.GOOD,
            imageKey = "untrustworthy_servant",
            mechanicSummary = "Appears suspicious in information systems despite being loyal.",
            tags = setOf("deception", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.ROGUE_GOOD,
            name = "Good Rogue",
            alignment = Alignment.GOOD,
            imageKey = "rogue_good",
            mechanicSummary = "Good half of the Rogue module with a unique win condition.",
            tags = setOf("rogue", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.SORCERER_GOOD,
            name = "Good Sorcerer",
            alignment = Alignment.GOOD,
            imageKey = "sorcerer_good",
            mechanicSummary = "Good half of the Sorcerer module.",
            tags = setOf("sorcerer", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.LOYAL_SERVANT,
            name = "Loyal Servant",
            alignment = Alignment.GOOD,
            imageKey = "loyal_servant",
            mechanicSummary = "No special power. Uses deduction during missions.",
            tags = setOf("core"),
        ),
        RoleDefinition(
            id = RoleId.ASSASSIN,
            name = "Assassin",
            alignment = Alignment.EVIL,
            imageKey = "assassin",
            mechanicSummary = "Attempts to identify Merlin after three successful missions.",
            tags = setOf("core", "kill"),
        ),
        RoleDefinition(
            id = RoleId.MORGANA,
            name = "Morgana",
            alignment = Alignment.EVIL,
            imageKey = "morgana",
            mechanicSummary = "Appears as Merlin to Percival.",
            tags = setOf("deception", "core"),
        ),
        RoleDefinition(
            id = RoleId.MORDRED,
            name = "Mordred",
            alignment = Alignment.EVIL,
            imageKey = "mordred",
            mechanicSummary = "Hidden from Merlin during the opening information phase.",
            tags = setOf("stealth", "core"),
        ),
        RoleDefinition(
            id = RoleId.OBERON,
            name = "Oberon",
            alignment = Alignment.EVIL,
            imageKey = "oberon",
            mechanicSummary = "Unknown to other evil players and does not know them.",
            tags = setOf("chaos", "core"),
        ),
        RoleDefinition(
            id = RoleId.LUNATIC,
            name = "Lunatic",
            alignment = Alignment.EVIL,
            imageKey = "lunatic",
            mechanicSummary = "An evil role constrained to fail every quest they join.",
            tags = setOf("expansion"),
        ),
        RoleDefinition(
            id = RoleId.BRUTE,
            name = "Brute",
            alignment = Alignment.EVIL,
            imageKey = "brute",
            mechanicSummary = "Can only fail within specific quest windows per expansion rules.",
            tags = setOf("expansion"),
        ),
        RoleDefinition(
            id = RoleId.TRICKSTER,
            name = "Trickster",
            alignment = Alignment.EVIL,
            imageKey = "trickster",
            mechanicSummary = "Uses loyalty-check misinformation as part of expansion play.",
            tags = setOf("deception", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.REVEALER,
            name = "Revealer",
            alignment = Alignment.EVIL,
            imageKey = "revealer",
            mechanicSummary = "Loyalty status becomes public at a trigger point in expansion rules.",
            tags = setOf("expansion"),
        ),
        RoleDefinition(
            id = RoleId.EVIL_MESSENGER,
            name = "Evil Messenger",
            alignment = Alignment.EVIL,
            imageKey = "evil_messenger",
            mechanicSummary = "Evil member of the Messenger trio with hidden alignment pressure.",
            tags = setOf("messenger", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.ROGUE_EVIL,
            name = "Evil Rogue",
            alignment = Alignment.EVIL,
            imageKey = "rogue_evil",
            mechanicSummary = "Evil half of the Rogue module and remains hidden from other evil during reveal.",
            tags = setOf("rogue", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.SORCERER_EVIL,
            name = "Evil Sorcerer",
            alignment = Alignment.EVIL,
            imageKey = "sorcerer_evil",
            mechanicSummary = "Evil half of the Sorcerer module and remains hidden from Merlin.",
            tags = setOf("sorcerer", "expansion"),
        ),
        RoleDefinition(
            id = RoleId.MINION,
            name = "Minion",
            alignment = Alignment.EVIL,
            imageKey = "minion",
            mechanicSummary = "No special power beyond being aligned with evil.",
            tags = setOf("core"),
        ),
        RoleDefinition(
            id = RoleId.LANCELOT_GOOD,
            name = "Good Lancelot",
            alignment = Alignment.GOOD,
            imageKey = "lancelot_good",
            mechanicSummary = "Can switch allegiance in module variants. Treat as good at start.",
            modules = setOf(GameModule.LANCELOT),
            tags = setOf("module", "lancelot"),
        ),
        RoleDefinition(
            id = RoleId.LANCELOT_EVIL,
            name = "Evil Lancelot",
            alignment = Alignment.EVIL,
            imageKey = "lancelot_evil",
            mechanicSummary = "Can switch allegiance in module variants. Treat as evil at start.",
            modules = setOf(GameModule.LANCELOT),
            tags = setOf("module", "lancelot"),
        ),
    ).associateBy(RoleDefinition::id)

    fun all(): List<RoleDefinition> = roles.values.sortedBy { it.name }

    fun byId(id: RoleId): RoleDefinition? = roles[id]

    fun byAlignment(alignment: Alignment): List<RoleDefinition> =
        roles.values.filter { it.alignment == alignment }.sortedBy { it.name }
}
