package com.avalonnarrator.domain.audio

object NarrationScriptCatalog {
    private val thematicLines: Map<ClipId, String> = mapOf(
        ClipId.INTRO to "Welcome to Avalon.",
        ClipId.CLOSE_EYES to "Everyone, close your eyes.",
        ClipId.HANDS_IN_FISTS to "Make a fist in front of you.",
        ClipId.CLERIC_LEADER_EVIL_THUMB to "Leader, if you are evil, extend your thumb now.",
        ClipId.CLERIC_OPEN_EYES to "Cleric, open your eyes.",
        ClipId.CLERIC_CLOSE_EYES to "Cleric, close your eyes.",
        ClipId.LEADER_RETURN_FIST to "Leader, return your hand to a fist.",
        ClipId.EVIL_WAKE to "Minions of Mordred, open your eyes and look for your allies.",
        ClipId.EVIL_WAKE_EXCEPT_EVIL_ROGUE to "Minions of Mordred, except the Evil Rogue, open your eyes and look for your allies.",
        ClipId.EVIL_CLOSE to "Minions of Mordred, close your eyes.",
        ClipId.ALL_KEEP_EYES_CLOSED_FISTS to "All players, keep eyes closed and hands in a fist.",
        ClipId.MINIONS_EXTEND_THUMB_FOR_MERLIN to "Minions of Mordred, extend your thumb for Merlin.",
        ClipId.MINIONS_EXTEND_THUMB_FOR_MERLIN_EXCEPT_EVIL_SORCERER to "Minions of Mordred, except the Evil Sorcerer, extend your thumb for Merlin.",
        ClipId.MINIONS_RETURN_FIST to "Minions of Mordred, return your hand to a fist.",
        ClipId.MINIONS_RETURN_FIST_EXCEPT_EVIL_SORCERER to "Minions of Mordred, except the Evil Sorcerer, return your hand to a fist.",
        ClipId.MERLIN_WAKE to "Merlin, open your eyes and observe the agents of evil.",
        ClipId.MERLIN_CLOSE to "Merlin, close your eyes.",
        ClipId.MERLIN_AND_MORGANA_EXTEND_THUMB to "Merlin and Morgana, extend your thumb.",
        ClipId.MERLIN_AND_MORGANA_RETURN_FIST to "Merlin and Morgana, return your hand to a fist.",
        ClipId.MERLIN_EXTEND_THUMB to "Merlin, extend your thumb.",
        ClipId.MERLIN_RETURN_FIST to "Merlin, return your hand to a fist.",
        ClipId.PERCIVAL_WAKE to "Percival, open your eyes.",
        ClipId.PERCIVAL_CLOSE to "Percival, close your eyes.",
        ClipId.LANCELOT_WAKE to "Lancelot players, open your eyes and find each other.",
        ClipId.LANCELOT_CLOSE to "Lancelot players, close your eyes.",
        ClipId.JUNIOR_MESSENGER_EXTEND_THUMB to "Junior Messenger, extend your thumb.",
        ClipId.SENIOR_MESSENGER_OPEN_EYES to "Senior Messenger, open your eyes.",
        ClipId.SENIOR_MESSENGER_CLOSE_EYES to "Senior Messenger, close your eyes.",
        ClipId.JUNIOR_MESSENGER_RETURN_FIST to "Junior Messenger, return your hand to a fist.",
        ClipId.UNTRUSTWORTHY_AND_MINIONS_EXTEND_THUMB to "Minions of Mordred and the Untrustworthy Servant, extend your thumb.",
        ClipId.UNTRUSTWORTHY_AND_MINIONS_RETURN_FIST to "Minions of Mordred and the Untrustworthy Servant, return your hand to a fist.",
        ClipId.ASSASSIN_EXTEND_THUMB_FOR_UNTRUSTWORTHY to "Assassin, extend your thumb so the Untrustworthy Servant can identify you.",
        ClipId.UNTRUSTWORTHY_OPEN_EYES to "Untrustworthy Servant, open your eyes.",
        ClipId.UNTRUSTWORTHY_CLOSE_EYES to "Untrustworthy Servant, close your eyes.",
        ClipId.ASSASSIN_RETURN_FIST to "Assassin, return your hand to a fist.",
        ClipId.LADY_OF_LAKE to "Lady of the Lake reminder: holder, choose one player to inspect.",
        ClipId.LADY_PASS_TOKEN to "Pass the Lady of the Lake token to the inspected player.",
        ClipId.EXCALIBUR to "Excalibur reminder: assign Excalibur to one questing player.",
        ClipId.EXCALIBUR_SWITCH_REMINDER to "Before cards are revealed, Excalibur may force one quest-card switch.",
        ClipId.ALL_OPEN to "Everyone, open your eyes.",
        ClipId.GAME_START to "The game begins.",
        ClipId.ROLE_REMINDER_MERLIN to "Reminder: Merlin knows most evil players, but must remain hidden.",
        ClipId.ROLE_REMINDER_ASSASSIN to "Reminder: if good completes three quests, Assassin makes the final guess.",
        ClipId.ROLE_REMINDER_MORDRED to "Reminder: Mordred stays hidden from Merlin.",
        ClipId.ROLE_REMINDER_OBERON to "Reminder: Oberon is evil but does not coordinate with evil allies.",
        ClipId.ROLE_REMINDER_MORGANA to "Reminder: Morgana appears as Merlin to Percival.",
        ClipId.ROLE_REMINDER_PERCIVAL to "Reminder: Percival sees Merlin and Morgana but cannot distinguish them.",
        ClipId.ROLE_REMINDER_LUNATIC to "Reminder: Lunatic must fail every quest joined.",
        ClipId.ROLE_REMINDER_BRUTE to "Reminder: Brute may fail only within the early quests.",
        ClipId.ROLE_REMINDER_REVEALER to "Reminder: Revealer must reveal identity after the second failed quest.",
        ClipId.ROLE_REMINDER_CLERIC to "Reminder: Cleric learns the leader's alignment during reveal.",
        ClipId.ROLE_REMINDER_TRICKSTER to "Reminder: Trickster may lie when loyalty is checked.",
        ClipId.ROLE_REMINDER_TROUBLEMAKER to "Reminder: Troublemaker must lie when loyalty is checked.",
        ClipId.ROLE_REMINDER_UNTRUSTWORTHY to "Reminder: Untrustworthy Servant can be recruited in endgame.",
        ClipId.ROLE_REMINDER_ROGUE to "Reminder: Rogue roles use alternate victory pressure in Rogue games.",
        ClipId.ROLE_REMINDER_MESSENGERS to "Reminder: Messenger module includes two good and one evil messenger.",
        ClipId.ROLE_REMINDER_SORCERERS to "Reminder: Sorcerer module adds one good and one evil sorcerer.",
        ClipId.ROLE_REMINDER_LANCELOTS to "Reminder: Lancelot allegiance may change in some variants.",
    )

    fun lineFor(clipId: ClipId): String =
        thematicLines[clipId] ?: clipId.name
            .split('_')
            .joinToString(" ") { token -> token.lowercase().replaceFirstChar(Char::titlecase) }
}
