package com.avalonnarrator.domain.audio

// AUTO-GENERATED by scripts/generate_voice_pack.py. Do not edit manually.
typealias VoicePackId = String

object VoicePackIds {
    const val WIZARD: VoicePackId = "wizard"
    const val RAINBIRD_EN: VoicePackId = "rainbird_en"
}

object VoicePackCatalog {
    val defaultPackId: VoicePackId = VoicePackIds.WIZARD

    private val packs: Map<VoicePackId, VoicePackDefinition> = listOf(
        VoicePackDefinition(
            id = VoicePackIds.WIZARD,
            displayName = "Wizard",
            description = "Deep theatrical narration with a dark-fantasy tone for full-table drama.",
            clipFiles = ClipId.entries.associateWith { clip ->
                "audio/wizard/${clip.name.lowercase()}.mp3"
            },
        ),
        VoicePackDefinition(
            id = VoicePackIds.RAINBIRD_EN,
            displayName = "Rainbird",
            description = "Calm British delivery with clear pacing and softer emphasis for readability.",
            clipFiles = ClipId.entries.associateWith { clip ->
                "audio/rainbird_en/${clip.name.lowercase()}.mp3"
            },
        ),
    ).associateBy { it.id }

    fun all(): List<VoicePackDefinition> = packs.values.toList()

    fun byId(id: VoicePackId): VoicePackDefinition? = packs[id]
}
