package com.avalonnarrator.domain.recommendation

import com.avalonnarrator.domain.roles.RoleId

object RecommendedLineupCatalog {
    private val allLineups: List<RecommendedLineupDefinition> = listOf(
        RecommendedLineupDefinition(
            id = "p5_classic_opening",
            title = "Classic Opening",
            playerCount = 5,
            description = "Baseline 5-player information duel: powerful Percival reads against Morgana's bluff.",
            flavor = LineupFlavor.BALANCED,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.ASSASSIN, RoleId.MORGANA),
            loyalServants = 1,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p5_oberon_smoke",
            title = "Oberon Smoke",
            playerCount = 5,
            description = "Oberon disrupts evil coordination, creating high social chaos in a short game.",
            flavor = LineupFlavor.CHAOTIC,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.ASSASSIN, RoleId.OBERON),
            loyalServants = 1,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p6_core_court",
            title = "Core Court",
            playerCount = 6,
            description = "Classic 6-player lineup with clear power spikes on both teams and strong mind-games.",
            flavor = LineupFlavor.BALANCED,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.ASSASSIN, RoleId.MORGANA),
            loyalServants = 2,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p6_mordred_pressure",
            title = "Mordred Pressure",
            playerCount = 6,
            description = "Mordred stays hidden from Merlin and reduces good certainty, pressuring mission reads.",
            flavor = LineupFlavor.FAVORS_EVIL,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.CLERIC, RoleId.ASSASSIN, RoleId.MORDRED),
            loyalServants = 1,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p7_tournament_core",
            title = "Tournament Core",
            playerCount = 7,
            description = "Popular competitive shell: strong information roles versus an elite evil core.",
            flavor = LineupFlavor.BALANCED,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.ASSASSIN, RoleId.MORGANA, RoleId.MORDRED),
            loyalServants = 2,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p7_oberon_gambit",
            title = "Oberon Gambit",
            playerCount = 7,
            description = "Adds Cleric value and introduces Oberon friction for swingier team-level coordination.",
            flavor = LineupFlavor.CHAOTIC,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.CLERIC, RoleId.ASSASSIN, RoleId.MORGANA, RoleId.OBERON),
            loyalServants = 1,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p8_royal_intrigue",
            title = "Royal Intrigue",
            playerCount = 8,
            description = "High-information loyal side meets hidden Mordred pressure for a tense mid-size table.",
            flavor = LineupFlavor.FAVORS_EVIL,
            specialRoles = setOf(RoleId.MERLIN, RoleId.PERCIVAL, RoleId.CLERIC, RoleId.ASSASSIN, RoleId.MORGANA, RoleId.MORDRED),
            loyalServants = 2,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p8_twin_lancelots",
            title = "Twin Lancelots",
            playerCount = 8,
            description = "Lancelot pair adds uncertainty and table drama while keeping core Merlin/Percival dynamics.",
            flavor = LineupFlavor.CHAOTIC,
            specialRoles = setOf(
                RoleId.MERLIN,
                RoleId.PERCIVAL,
                RoleId.LANCELOT_GOOD,
                RoleId.ASSASSIN,
                RoleId.MORGANA,
                RoleId.LANCELOT_EVIL,
            ),
            loyalServants = 2,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p9_high_council",
            title = "High Council",
            playerCount = 9,
            description = "Deep read-heavy game with Cleric and Untrustworthy Servant layered onto core identities.",
            flavor = LineupFlavor.BALANCED,
            specialRoles = setOf(
                RoleId.MERLIN,
                RoleId.PERCIVAL,
                RoleId.CLERIC,
                RoleId.UNTRUSTWORTHY_SERVANT,
                RoleId.ASSASSIN,
                RoleId.MORGANA,
                RoleId.MORDRED,
            ),
            loyalServants = 2,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p9_messenger_network",
            title = "Messenger Network",
            playerCount = 9,
            description = "Messenger trio creates directional info leaks and counter-bluffs around the board.",
            flavor = LineupFlavor.CHAOTIC,
            specialRoles = setOf(
                RoleId.MERLIN,
                RoleId.PERCIVAL,
                RoleId.SENIOR_MESSENGER,
                RoleId.JUNIOR_MESSENGER,
                RoleId.ASSASSIN,
                RoleId.MORGANA,
                RoleId.EVIL_MESSENGER,
            ),
            loyalServants = 2,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p10_grand_classic",
            title = "Grand Classic",
            playerCount = 10,
            description = "Full-table classic tension with Mordred hidden info and Oberon disruption in the same game.",
            flavor = LineupFlavor.BALANCED,
            specialRoles = setOf(
                RoleId.MERLIN,
                RoleId.PERCIVAL,
                RoleId.CLERIC,
                RoleId.ASSASSIN,
                RoleId.MORGANA,
                RoleId.MORDRED,
                RoleId.OBERON,
            ),
            loyalServants = 3,
            minions = 0,
        ),
        RecommendedLineupDefinition(
            id = "p10_arcane_war",
            title = "Arcane War",
            playerCount = 10,
            description = "Rogue and Sorcerer pairs create a volatile late-game with layered deception pressure.",
            flavor = LineupFlavor.CHAOTIC,
            specialRoles = setOf(
                RoleId.MERLIN,
                RoleId.PERCIVAL,
                RoleId.SORCERER_GOOD,
                RoleId.ROGUE_GOOD,
                RoleId.ASSASSIN,
                RoleId.MORGANA,
                RoleId.SORCERER_EVIL,
                RoleId.ROGUE_EVIL,
            ),
            loyalServants = 2,
            minions = 0,
        ),
    )

    fun forPlayerCount(playerCount: Int): List<RecommendedLineupDefinition> =
        allLineups.filter { it.playerCount == playerCount }

    fun all(): List<RecommendedLineupDefinition> = allLineups
}
